### ISSUE TITLE
[HELP] How can I link key frame object ?

### ISSUE THREAD

**Issue by tbvns** [iAndyHD3/WSLiveEditor#10]
I want to make some object move with keyframes, but I can't figure out how to link two keyframes with this mod.

Is there something special I need to do ?

**Comment by iAndyHD3** [comment]
this mod does not really do anything special, it just takes object strings and creates them using gd functions. the format of the string is exactly the same as when the level is saved to a string. i suggest you take a look at the uncompressed string of your level

**Comment by tbvns** [comment]
> this mod does not really do anything special, it just takes object strings and creates them using gd functions. the format of the string is exactly the same as when the level is saved to a string. i suggest you take a look at the uncompressed string of your level

Is there a tool to see that ?

Edit: I found how to get the level string, it is supposed to be encrypted in base64 but when I try to decide it, it just gives me garbage.

**Comment by Geming400** [comment]
@tbvns You could look at this:
https://wyliemaster.github.io/gddocs/#/topics/encryption/robtop-cipher

And also maybe this:
https://wyliemaster.github.io/gddocs/#/topics/localfiles_encrypt_decrypt

**Comment by tbvns** [comment]
Yea I asked the guy that made the website with all the new objects strings if he could find it and he said yes, now this is on the websites

Edit: I'm talking about https://flowvix.github.io/gd-info-explorer/
