### ISSUE TITLE
I cannot enter the websocket

### ISSUE THREAD

**Issue by RorutopThe2nd** [iAndyHD3/WSLiveEditor#11]
I read the wiki FAQ, but I'm still not able to enter the host when I'm in the editor..
![image](https://github.com/iAndyHD3/WSLiveEditor/assets/162891810/51d2c4bc-0f69-4226-ab53-5501991a0525)
![image](https://github.com/iAndyHD3/WSLiveEditor/assets/162891810/92823e20-dcde-406c-bf33-12018a4e62b6)

**Comment by tbvns** [comment]
Web socket cannot be accessed like that, it is supposed to be used by programs to send information. You need to create a web socket client or download one to use this mod.

Take a look at the [examples](https://github.com/iAndyHD3/WSLiveEditor/wiki/Examples) section of the wiki.
