### ISSUE TITLE
GAME CRASH

### ISSUE THREAD

**Issue by QiuiYT** [iAndyHD3/WSLiveEditor#2]
Game Crash:

2024-02-10T15:37:13+0100
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "iandyhd3.wsliveeditor" mod. Please submit this crash report to its developers (iAndyHD3) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.17
Loader Commit: 032f133
Bindings Commit: a48ac28
Installed mods: 77
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\pc\Downloads\Geometry Dash 2.205\geode\unzipped\iandyhd3.wsliveeditor\iandyhd3.wsliveeditor.dll
Faulty Mod: iandyhd3.wsliveeditor
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 5D63D5CC (iandyhd3.wsliveeditor.dll + d5cc)
Number Parameters: 2

== Stack Trace ==
 - C:\Users\pc\Downloads\Geometry Dash 2.205\geode\unzipped\iandyhd3.wsliveeditor\iandyhd3.wsliveeditor.dll + d5cc
 - C:\Users\pc\Downloads\Geometry Dash 2.205\geode\unzipped\iandyhd3.wsliveeditor\iandyhd3.wsliveeditor.dll + 12a53
 - C:\Users\pc\Downloads\Geometry Dash 2.205\geode\unzipped\iandyhd3.wsliveeditor\iandyhd3.wsliveeditor.dll + 17d6
 - 0E470237
 - C:\Users\pc\Downloads\Geometry Dash 2.205\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 999a
 - 0E470237
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + ad27d (cocos2d::CCMenu::ccTouchEnded + 29)
 - 0E480EA6
 - C:\Users\pc\Downloads\Geometry Dash 2.205\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 7f8d4
 - 0E480CCF
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + be92c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + c7922 (cocos2d::CCEGLView::onGLFWMouseCallBack + 210)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + c794e (cocos2d::CCEGLView::onGLFWMouseCallBack + 254)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + 116cc9 (cocos2d::CCPoint::unrotate + 8073)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + 118819 (cocos2d::CCPoint::unrotate + 15065)
 - C:\Windows\System32\USER32.dll + 4120b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 381ca (GetClassLongW + 1978)
 - C:\Windows\System32\USER32.dll + 37897 (GetSystemMetricsForDpi + 5959)
 - C:\Windows\System32\USER32.dll + 35a3b (CallWindowProcW + 27)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 4696f (glDebugEntry + 3631)
 - C:\Windows\System32\USER32.dll + 4120b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 381ca (GetClassLongW + 1978)
 - C:\Windows\System32\USER32.dll + 35f2a (DispatchMessageW + 586)
 - C:\Windows\System32\USER32.dll + 35cf0 (DispatchMessageW + 16)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\GeometryDash.exe + 3c12d8
 - C:\Users\pc\Downloads\Geometry Dash 2.205\Geode.dll + c7806 (geode::utils::web::AsyncWebRequest::userAgent + 12406)
 - C:\Users\pc\Downloads\Geometry Dash 2.205\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 00000000
EBX: 00abf45c
ECX: 77af1cfc
EDX: 00000000
EBP: 004ff288
ESP: 004ff24c
EDI: 00abf45c
ESI: 00abf640
EIP: 5d63d5cc

== Installed Mods ==
x | [v1.0.3] adam_729.deathmarkers
x | [v1.1.1] adyagd.godlikefaces
  | [v1.0.0] adyagd.ingamelistmod
x | [v1.1.1] alphalaneous.deathlink
  | [v1.3.4] alphalaneous.integratedloquibot
x | [v1.0.0] alphalaneous.playercolorselect
  | [v1.1.2] alphalaneous.projectedstars
  | [v1.0.2] arkane.dl-team-icons
x | [v1.0.0] asaki_zuki.same_dual_color
x | [v1.4.0] beat.click-sound
x | [v1.0.5] bitz.customprofiles
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.2] capeling.demons_in_garage_2.2
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.0.1] coderqc.gdswearfilter
  | [v1.0.2] colon.bumpscosity
x | [v1.0.1] colon.gold_user_coins
  | [v1.0.1] creo.small-gd-mods
x | [v4.0.0-alpha.13] cvolton.betterinfo
x | [v1.0.5] dankmeme.globed2
  | [v1.1.1] ekv.hidePauseMenuHack
  | [v1.0.0] ekv.save_on_level_page
  | [v1.2.2] elnexreal.copy_song_id
x | [v1.0.0] elnexreal.demonlistinfo
x | [v1.4.3] elohmrow.death_tracker
x | [v1.0.3] firee.GoldenBest
  | [v1.4.1] firee.PrismMenu
x | [v2.4.0] fleym.nongd
  | [v1.2.14] gdutilsdevs.gdutils
x | [v1.4.0] geode.custom-keybinds
x | [v2.0.0-beta.17] geode.loader
x | [v1.3.0] geode.node-ids
x | [v1.5.0] geode.texture-loader
  | [v1.0.4] hjfod.gdshare
x | [v1.0.1] hjfod.gmd-api
x | [v1.0.1] iandyhd3.wsliveeditor
  | [v1.0.1] itzkiba.elegant_rankings
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
  | [v1.0.0] izzy.i_hate_you_top_lists
  | [v1.0.0] izzy.practice_sync
x | [v1.0.0] jojo989.main_menu_bg_customizer
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.2] mat.run-info
  | [v1.1.0] mat.scroll-zoom
x | [v2.4.6] maxnu.gd_mega_overlay
x | [v1.0.0-beta.2] minemaker0430.gddp_integration
  | [v1.0.4-beta.12] muhammadgames.bettermenu
x | [v1.0.2] ninkaz.blending_glow
x | [v1.0.0] nyakofox.channelviewer
x | [v1.2.1] oatmealine.ids_integration
  | [v1.2.0] oatmealine.nlw_integration
  | [v1.2.0-beta.4] org.dogotrigger.deathreplay
x | [v1.0.0] polsk.boring_delay_info
x | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
x | [v1.0.0] raydeeux.loadingscreentweaks
  | [v1.1.0] redlime.statchanges
x | [v1.2.0] sanes.daily-transfer
x | [v1.0.0] shadyiscool.shadypause
x | [v1.6.2] spaghettdev.gd-roulette
x | [v0.1.0] sse2.gj-music-manager
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.1.0] thesillydoggo.better_startpos_menu
  | [v1.1.3] TheSillyDoggo.Cheats
x | [v1.0.0] thesillydoggo.entersearch
x | [v2.1.0] TheSillyDoggo.GradientPages
  | [v1.0.0] TheSillyDoggo.StartposSwitcher
x | [v1.7.1] undefined0.gdtweaks
  | [v1.1.0] undefined0.minecraft_menu
x | [v1.1.1] uproxide.geodedevelopers
x | [v1.0.2] weebify.coins_in_pause_menu
x | [v1.0.1] weebify.level_info_in_pause_menu
  | [v1.0.1] weebify.randomizecreatorlayer-geode
x | [v1.0.0] xanii.youtubers
x | [v1.3.10] zilko.xdbot

**Comment by iAndyHD3** [comment]
as in the about section of the index, disable the mod if you are not using it (its for more advanced people)
