### ISSUE TITLE
Object-string wiki is not up-to-date !

### ISSUE THREAD

**Issue by tbvns** [iAndyHD3/WSLiveEditor#3]
I know this is not your fault, but I wanted to ask if there was any updated wiki for 2.2.

**Comment by iAndyHD3** [comment]
what do you mean exactly by object string wiki?

it has not really changed much, only new object properties were added. look at the [gd docs](https://wyliemaster.github.io/gddocs/#/resources/client/level-components/level-object?id=object-string). There's also an updated [object property list](https://flowvix.github.io/gd-info-explorer/) with 2.2 properties

**Comment by tbvns** [comment]
That's exactly what I wanted, thsm for the updated list.
