### ISSUE TITLE
[FEATURE REQUEST] Add custom color changing

### ISSUE THREAD

**Issue by tbvns** [iAndyHD3/WSLiveEditor#5]
For my current project, I need to be able to change the custom color of the level. I thought at first I'd make a fork of this mod to do that and not request someone else to do my job. But I don't know C++ and the GeodeSDK.

The request could look something like this:
```json
{
  "action": "COLOR",
  "id": "id",
  "color": "r,g,b"
}
```

so it would look something like this:
```json
{
  "action": "COLOR",
  "id": "5",
  "color": "20,58,204"
}
```

**Comment by iAndyHD3** [comment]
sure! will get around adding this soon. let me know if you have more feature requests

**Comment by iAndyHD3** [comment]
let me know if there are any issues (i could not really test much)
