### ISSUE TITLE
[FEATURE REQUEST] Add wiki

### ISSUE THREAD

**Issue by tbvns** [iAndyHD3/WSLiveEditor#6]
Since this mod will have more and more function, it might be better to add a wiki with GitHub wiki option. I tried to make something quickly, but since I'm not native, someone will need to correct all the grammatical mistake.

Here is what i made:
[https://github.com/tbvns/WSLiveEditor/wiki](https://github.com/tbvns/WSLiveEditor/wiki)

**Comment by iAndyHD3** [comment]
thanks a lot, will add to the main repo

**Comment by iAndyHD3** [comment]
added the wiki with some changes
