### ISSUE TITLE
Dead link in the wiki and new banner

### ISSUE THREAD

**Issue by tbvns** [iAndyHD3/WSLiveEditor#8]
There is a dead link in the FAQ the was supposed to redirect to the "How to use this mod" page, I think it should be changed to "Example".

Also, the logo in readme.md looked a bite strange like this, so I made a banner, but I wanted to ask before making another pull request.

Here is what I made:
![banner2](https://github.com/iAndyHD3/WSLiveEditor/assets/69420062/5364f9bd-cbff-4042-a6db-d88235514554)

**Comment by iAndyHD3** [comment]
I think i enabled everyone permission to edit the wiki, can you check? https://github.com/iAndyHD3/WSLiveEditor/wiki
you can fix the link and add the banner ye

**Comment by tbvns** [comment]
> I think i enabled everyone permission to edit the wiki, can you check? https://github.com/iAndyHD3/WSLiveEditor/wiki you can fix the link and add the banner ye

I edited the wiki to fix the dead link and I also opened a pull request for the banner.
